/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module tiny_alu(clk, op, a, b, y);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  input [3:0] a;
  wire [3:0] a_reg;
  input [3:0] b;
  wire [3:0] b_reg;
  input clk;
  input op;
  output [3:0] y;
  NAND3_X1 _21_ (
    .A1(b_reg[0]),
    .A2(a_reg[0]),
    .A3(op),
    .ZN(_01_)
  );
  XNOR2_X1 _22_ (
    .A(b_reg[0]),
    .B(a_reg[0]),
    .ZN(_02_)
  );
  OAI21_X1 _23_ (
    .A(_01_),
    .B1(_02_),
    .B2(op),
    .ZN(_00_[0])
  );
  NAND3_X1 _24_ (
    .A1(op),
    .A2(b_reg[1]),
    .A3(a_reg[1]),
    .ZN(_03_)
  );
  XNOR2_X1 _25_ (
    .A(b_reg[1]),
    .B(a_reg[1]),
    .ZN(_04_)
  );
  OAI21_X1 _26_ (
    .A(_03_),
    .B1(_04_),
    .B2(op),
    .ZN(_00_[1])
  );
  NAND3_X1 _27_ (
    .A1(op),
    .A2(b_reg[2]),
    .A3(a_reg[2]),
    .ZN(_05_)
  );
  XNOR2_X1 _28_ (
    .A(b_reg[2]),
    .B(a_reg[2]),
    .ZN(_06_)
  );
  OAI21_X1 _29_ (
    .A(_05_),
    .B1(_06_),
    .B2(op),
    .ZN(_00_[2])
  );
  NAND3_X1 _30_ (
    .A1(op),
    .A2(b_reg[3]),
    .A3(a_reg[3]),
    .ZN(_07_)
  );
  XNOR2_X1 _31_ (
    .A(b_reg[3]),
    .B(a_reg[3]),
    .ZN(_08_)
  );
  OAI21_X1 _32_ (
    .A(_07_),
    .B1(_08_),
    .B2(op),
    .ZN(_00_[3])
  );
  DFF_X1 _33_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(y[0]),
    .QN(_14_)
  );
  DFF_X1 _34_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(y[1]),
    .QN(_15_)
  );
  DFF_X1 _35_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(y[2]),
    .QN(_16_)
  );
  DFF_X1 _36_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(y[3]),
    .QN(_17_)
  );
  DFF_X1 _37_ (
    .CK(clk),
    .D(a[0]),
    .Q(a_reg[0]),
    .QN(_18_)
  );
  DFF_X1 _38_ (
    .CK(clk),
    .D(a[1]),
    .Q(a_reg[1]),
    .QN(_19_)
  );
  DFF_X1 _39_ (
    .CK(clk),
    .D(a[2]),
    .Q(a_reg[2]),
    .QN(_20_)
  );
  DFF_X1 _40_ (
    .CK(clk),
    .D(a[3]),
    .Q(a_reg[3]),
    .QN(_09_)
  );
  DFF_X1 _41_ (
    .CK(clk),
    .D(b[0]),
    .Q(b_reg[0]),
    .QN(_10_)
  );
  DFF_X1 _42_ (
    .CK(clk),
    .D(b[1]),
    .Q(b_reg[1]),
    .QN(_11_)
  );
  DFF_X1 _43_ (
    .CK(clk),
    .D(b[2]),
    .Q(b_reg[2]),
    .QN(_12_)
  );
  DFF_X1 _44_ (
    .CK(clk),
    .D(b[3]),
    .Q(b_reg[3]),
    .QN(_13_)
  );
endmodule
